services:
  mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db

  blog-app-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/blog-app
      - PORT=5000
    depends_on:
      - mongo

  blog-app-frontend:
    build:
      context: ../frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://blog-app-backend:5000
    depends_on:
      - blog-app-backend