name: Deploy Backend
on: 
  push: 
      branches: ["master", "main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout to branch"
        uses: actions/checkoutV2

      - name: "Dockerhub login"
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: "Push image to dockerhub"
        uses: docker/build-push-action@v4
        with: 
          context: ./backend
          file: ./backend/Dockerfile
          push: true